### PR TITLE
fix(editor): route EntityIdToObject call sites through UnityObjectIdCompat (Unity 6000.0-6000.2 compile break)

### PR DESCRIPTION
**Pull request by ducyb294**
## Problem

`MCPForUnity.Editor` fails to compile on Unity 6000.0–6000.2, so the bridge never starts and the MCP server reports "No Unity Editor instances found":

```
InputTargetResolver.cs(121,48): error CS0117: 'EditorUtility' does not contain a definition for 'EntityIdToObject'
ManageMesh.cs(232,36): error CS0117: 'EditorUtility' does not contain a definition for 'EntityIdToObject'
ManageTerrain.cs(411,52): error CS0117: 'EditorUtility' does not contain a definition for 'EntityIdToObject'
```

`EditorUtility.EntityIdToObject` only exists from Unity 6000.3. Commit 18f39d6 (#35) assumed it was available on 6.0+ and left these three call sites bare.

Verified against installed editors: `6000.2.10f1/Editor/Data/Managed/UnityEditor.dll` has no `EntityIdToObject` symbol; `6000.3.15f1` does.

## Fix

Route the three call sites through the existing `UnityObjectIdCompat.InstanceIDToObjectCompat` shim, which already version-gates:

- `< 6000.3` → `EditorUtility.InstanceIDToObject(int)`
- `6000.3–6000.5` → `EditorUtility.EntityIdToObject`
- `6000.6+` → reflection path

No behaviour change on 6000.3+.

## Test

Reproduced on TrickyPuzzle (Unity 6000.2.10f1) with the `beta` HEAD pin; after pinning this commit the package compiles and the bridge starts.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_017c9eUVfibTkuwjwM6ff5Py

### CODE REVIEW

**Comment by ducyb294** [comment]
Closing: project will upgrade to Unity 6000.3 instead, where EditorUtility.EntityIdToObject exists. Fix not needed on that path.
