### ISSUE TITLE
com.coplaydev.unity-mcp@beta does not compile on Unity 6000.5.7f1 — Editor bridge never starts, project registers no MCP instance

### ISSUE THREAD

**Issue by tuha263** [The1Studio/unity-mcp#61]
## Symptom

After bumping the `com.coplaydev.unity-mcp` submodule to `f6ffa19a` (branch `beta`) in a Unity **6000.5.7f1** project, the Editor bridge never starts. `mcpforunity://instances` lists only an *unrelated* project's editor, and the affected project has no listener on the 6400-range port — so every MCP tool call silently routes to whatever other Unity instance happens to be registered.

That mis-routing is the dangerous part: `manage_packages` / `refresh_unity` calls intended for project A were accepted and executed against project B, with no error and no warning. The only tell was `manage_packages ping` reporting a `unity_version` that did not match the target project's `ProjectVersion.txt`.

## Root cause

The package's Editor assembly fails to compile against Unity 6000.5. `Logs/Editor.log` shows 99 CS errors under `com.coplaydev.unity-mcp-pkg`, including:

- `Editor/Tools/ManageInputSimulation.cs(47,81): error CS0103` and `(48,39): CS0103`, `(48,21): CS0165`
- `Editor/Tools/ManageAsset.cs(1149,20): error CS0619` — obsolete-as-error (`GetInstanceID` / `InstanceIDToObject` were obsoleted in Unity 6000.5)
- further `CS0122`, `CS0428`, `CS0117` in the same package

It also declares assembly references that do not resolve in a URP project: `Unity.Entities`, `Unity.InputSystem`, `Unity.RenderPipelines.HighDefinition.Runtime`, `Newtonsoft.Json`. `com.unity.inputsystem` and `com.unity.entities` are not present in the consumer's manifest, so those references dangle and the assembly cannot build even before the CS errors.

## Asks (in priority order)

1. **Make the Editor assembly compile on Unity 6000.5.x** — replace the obsoleted `GetInstanceID` / `InstanceIDToObject` usages and fix the `ManageInputSimulation.cs` CS0103 / CS0165 errors.
2. **Gate optional integrations** behind `versionDefines` / `defineConstraints` so a URP project without Entities / InputSystem / HDRP still builds the bridge, rather than failing wholesale.
3. **Safety:** when a tool call targets an instance whose `unity_version` or project path does not match the caller's expectation, surface it. Silent cross-project routing when only one instance is registered is a footgun — consider requiring an explicit `set_active_instance` (or erroring) when the registered instance's project path differs from the client's working directory.

## Also worth flagging

The consumer's `manifest.json` points at `file:com.coplaydev.unity-mcp-pkg` while the git submodule lives at `Packages/com.coplaydev.unity-mcp` — two directories, both present. Whether that duplication is intended is unclear from the consumer side.

## Environment

- Unity **6000.5.7f1**, URP, Linux
- `com.coplaydev.unity-mcp` submodule at `f6ffa19a`, branch `beta`

**Comment by frostbun** [comment]
**Ask 3 (silent cross-project routing) is fixed by #81** — merged to `beta` as `986b772`. Leaving this issue open: asks 1 and 2 are untouched and both need an environment CI cannot currently provide.

**What #81 does.** When exactly one Unity instance is registered, the middleware selected it unconditionally on both the PluginHub and stdio paths — the cwd guard from #66 is only reached in the `len(ids) > 1` branch, which is not this scenario. It now refuses when the sole instance's project shares no ancestry with the session's cwd, naming both paths in the error. Only *provably disjoint* paths are refused, so launching from inside the project, at its root, or from a monorepo root above it all still auto-select; an unknown `project_path` is never treated as unrelated. Opt out with `UNITY_MCP_ALLOW_CROSS_PROJECT_AUTOSELECT=1`.

**What is left, and why it could not be cleared from source.** Verified against `beta` @ `b0fe829` rather than assumed:

- **Ask 1** — the `ManageAsset.cs` CS0619 arm *is* fixed (#64): `ManageAsset.cs:1148` now calls `IsLoadingAssetPreviewCompat()`, shimmed behind `UNITY_6000_5_OR_NEWER`. The `ManageInputSimulation.cs` CS0103/CS0165 arm is **not** explained by the optional-dependency theory in the comment above: `git diff f6ffa19a..beta` over `ManageInputSimulation.cs` and `InputSimulation/` is **empty** (byte-identical to the version that failed), and `InputSimulationFocusGuard.cs` contains no `#if` directives at all — it was never gated behind `UNITY_INPUT_SYSTEM` and uses only `UnityEditor`/`UnityEditorInternal` APIs. The sibling files that *do* need the package (`InputSimulationActions.cs`, `InputSimulationTouch.cs`) carry proper `#if UNITY_INPUT_SYSTEM` / `#else` fallbacks.

  Before editing anything here, it is worth testing the "Also worth flagging" note in the report: `manifest.json` pointing at `file:com.coplaydev.unity-mcp-pkg` while the submodule sits at `Packages/com.coplaydev.unity-mcp` means two copies of the package were present, and a stale copy predating `InputSimulationFocusGuard.cs` produces exactly CS0103 at those lines. A clean single-copy checkout on a 6000.5.x editor would settle it either way.

- **Ask 2** — `MCPForUnity.Editor.asmdef` is also byte-identical to the reported commit and still lists `Unity.Entities` / `Unity.InputSystem` / `Newtonsoft.Json` unconditionally under `references`. Choosing a fix shape needs a bare URP project with neither `com.unity.inputsystem` nor `com.unity.entities` to establish whether Unity errors or merely warns on the unresolved names. One correction: `Unity.RenderPipelines.HighDefinition.Runtime` appears in no MCPForUnity asmdef on `beta` — only in the vendored `TestProjects/AssetStoreUploads` asmdef, so that part of the report is misattributed.

- **No gate covers 6000.5.** `tools/unity-versions.json` carries a `$coverageGap` field stating the `UNITY_6000_5_OR_NEWER` / `UNITY_6000_6_OR_NEWER` branches are unexercised because GameCI has published no image; the matrix is 2021.3.45f2 / 2022.3.62f1 / 6000.0.75f1 / 6000.4.8f1. That standing TODO is why this reached a consumer instead of a gate — worth splitting out as its own issue.
